APP_NAME=LMPAY
APP_VERSION=1.0.0
BUILD_NUMBER=5
BUILD_DATE=2026-01-06
APP_KEY=RBLFkups6XW0bpAA3iD4pVoSQBJ4szTmZbbYouQSXBrSBn0lVWjvEV5sbt4dNGvkxNVYJGt5RUAQdHs7Qd+LjQ==
APP_BRANCH_CODE=00001
BASE_URL=http://103.121.26.154:5000/fz-api/

DEEPLINK_SCHEME_1=lmpay
DEEPLINK_SCHEME_2=lmpayDoc
DEEPLINK_SCHEME_3=lmpayDash


UAE_PASS=https://stg-id.uaepass.ae/idshub/
UAE_PASS_ClientId=sharaf_exchange_mob_stage
UAE_PASS_ClientSecret=Qk4TgGJs84fIEyyq
UAE_PASS_RedirectURL=https://mobileuat.sharafexchange.com/Payment/PaymentResponse/PostResponseUAEPASSRedirect
UAE_PASS_Scope=urn:uae:digitalid:profile urn:uae:digitalid:digitalvault:datasharerequest
UAE_PASS_UrlScheme=sharafExchange
UAE_PASS_State=HnlHOJTkTb66Y5H
UAE_PASS_IsProduction=false


AES_IV=bsxnWolsAyO7kCfWuyrnqg==
AES_KEY=AXe8YwuIn1zxt3FPWTZFlAa14EHdPAdN9FaZ9RQWihc=


FIREBASE_API_KEY_ANDROID = AIzaSyCegGjRgEHvMh9fZ7HSe2bl2ZN9zfwLAPg
FIREBASE_APP_ID_ANDROID = 1:283893584957:android:63f09d465eaf8489ac0654
FIREBASE_ANDROID_CLIENT_ID = 200925117312-kd29sg3rearvq1q65e4offrgqcaqth3m.apps.googleusercontent.com

FIREBASE_API_KEY_IOS = AIzaSyAB9H-uuWbglPaECwkR0j_OojonM6Z5e1c
FIREBASE_APP_ID_IOS = 1:283893584957:ios:5b41ef474f6de0b9ac0654
FIREBASE_IOS_BUNDLE_ID = com.user.lmpay
FIREBASE_IOS_CLIENT_ID = 200925117312-kd29sg3rearvq1q65e4offrgqcaqth3m.apps.googleusercontent.com

FIREBASE_API_KEY_WINDOWS = AIzaSyCiL4iLWGl7POVW8FIW0MhllUb3OCaqLhA
FIREBASE_APP_ID_WINDOWS = 1:283893584957:web:a2032f9f5464341fac0654

FIREBASE_API_KEY_MACOS = AIzaSyAB9H-uuWbglPaECwkR0j_OojonM6Z5e1c
FIREBASE_APP_ID_MACOS = 1:283893584957:ios:5b41ef474f6de0b9ac0654

FIREBASE_MESSAGING_SENDER_ID = 283893584957
FIREBASE_PROJECT_ID = lm-user-app
FIREBASE_DATABASE_URL = https://lm-user-app-default-rtdb.asia-southeast1.firebasedatabase.app
FIREBASE_STORAGE_BUCKET = lm-user-app.firebasestorage.app
FIREBASE_AUTH_DOMAIN = lm-user-app.firebaseapp.com
FIREBASE_MEASUREMENT_ID: G-EQZCVRDFPS