// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'transaction_details_fz.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_TransactionFz _$TransactionFzFromJson(Map<String, dynamic> json) =>
    _TransactionFz(
      statusCode: json['StatusCode'] as String? ?? '',
      statusMessage: json['StatusMessage'] as String? ?? '',
      pageSize: (json['PageSize'] as num?)?.toInt() ?? 0,
      currentPage: (json['CurrentPage'] as num?)?.toInt() ?? 0,
      totalPages: (json['TotalPages'] as num?)?.toInt() ?? 0,
      totalCount: (json['TotalCount'] as num?)?.toInt() ?? 0,
      data: (json['Data'] as List<dynamic>?)
              ?.map((e) =>
                  TransactionDetailsFz.fromJson(e as Map<String, dynamic>))
              .toList() ??
          const [],
    );

Map<String, dynamic> _$TransactionFzToJson(_TransactionFz instance) =>
    <String, dynamic>{
      'StatusCode': instance.statusCode,
      'StatusMessage': instance.statusMessage,
      'PageSize': instance.pageSize,
      'CurrentPage': instance.currentPage,
      'TotalPages': instance.totalPages,
      'TotalCount': instance.totalCount,
      'Data': instance.data,
    };

_TransactionDetailsFz _$TransactionDetailsFzFromJson(
        Map<String, dynamic> json) =>
    _TransactionDetailsFz(
      transactionReference: json['ReferenceNo'] as String?,
      chqNo: json['ChqNo'] as String?,
      transactionDate: _fromJsonDateTime(json['TranDate'] as String?),
      customerName: _readCustName(json, 'CustomerName') as String?,
      custFirstName: json['CustomerFirstName'] as String?,
      custMiddleName: json['CustomerMiddleName'] as String?,
      custLastName: json['CustomerLastName'] as String?,
      beneficiaryName: _readBenefName(json, 'BeneficiaryName') as String?,
      benfFirstName: json['BenfName'] as String?,
      benfMiddleName: json['BenfName2'] as String?,
      benfLastName: json['BenfName3'] as String?,
      benfCountry: json['BenfCountry'] as String?,
      toCurrencyCode: json['BenfCurrencyCode'] as String?,
      fromCurrencyCode: json['CurrencyCode'] as String?,
      accountNumber: json['AccountNo'] as String?,
      bankName: json['BankName'] as String?,
      paymentAmount: (json['FcyAmount'] as num?)?.toDouble(),
      receivedAmount: json['LcyAmount'] as String?,
      charge: json['Charges'] as String?,
      taxAmount: (json['TaxAmount'] as num?)?.toDouble(),
      netAmount: (json['NetAmount'] as num?)?.toDouble(),
      multiplicationRate: (json['MultiplicationRate'] as num?)?.toDouble(),
      beneficiaryMobile: json['BeneficiaryMobile'] as String?,
      servMode: json['ServMode'] as String?,
      pinNumber: json['PinNumber'] as String?,
      payMode: json['PayMode'] as String?,
      payModeDesc: json['PayModeDesc'] as String?,
      paymentStatus: json['PaymentStatus'] as String?,
      bneficiaryId: json['BneficiaryId'] as String?,
      serviceCode: json['ServiceCode'] as String?,
      serviceType: json['ServiceType'] as String?,
      benfActiveStatus: json['BenfActiveStatus'] as String?,
      readyForCancel: json['ReadyForCancel'] as String?,
      transactionStatus: json['TransactionStatus'] as String?,
      serviceProvider: json['ServiceProvider'] as String?,
      paymentRefNo: json['PaymentRefNo'] as String?,
      divisionRate: (json['DivisionRate'] as num?)?.toDouble(),
      header: json['Header'] as String?,
      isMobileTxn: json['IsMobileTxn'] as bool?,
      isCorrespondentActive: json['IsCorrespondentActive'] as String?,
      branchName: json['BranchName'] as String?,
      purpose: json['Purpose'] as String?,
      ifscCode: json['IfscCode'] as String?,
      rebate: json['Rebate'] as String?,
      branchCode: json['BranchCode'] as String?,
      customer: json['Customer'] as String?,
      email: json['Email'] as String?,
      taxCard: json['TaxCard'] as String?,
      customerVatin:
          (_readCustomerVatin(json, 'CustomerVatin') as num?)?.toDouble(),
      arieEmployeeFlag: json['ArieEmployeeFlag'] as String?,
      relationship: json['Relationship'] as String?,
      destinationCountryCode: json['DestinationCountryCode'] as String?,
      destinationCountry: json['DestinationCountry'] as String?,
      cr: json['CR'] as String?,
      customerNationality: json['CustomerNationality'] as String?,
      customerNationalityCode: json['CustomerNationalityCode'] as String?,
      source: json['Source'] as String?,
      beneficiaryNationality: json['BeneficiaryNationality'] as String?,
      beneficiaryAddress: json['BeneficiaryAddress'] as String?,
      beneficiaryCountryCode: json['BeneficiaryCountryCode'] as String?,
      correspondent: json['Correspondent'] as String?,
      profession: json['Profession'] as String?,
      beneficiaryType: json['BeneficiaryType'] as String?,
      customerIdDescription: json['CustomerIdDescription'] as String?,
      visaType: json['VisaType'] as String?,
      customerType: json['CustomerType'] as String?,
      branchId: json['BranchId'] as String?,
      birthCountryCode: json['BirthCountryCode'] as String?,
      birthCountry: json['BirthCountry'] as String?,
      customerIdNo: json['CustomerIdNo'] as String?,
      customerCode: json['CustomerCode'] as String?,
      isPep: json['IsPep'] as String?,
      idCode: json['IdCode'] as String?,
      paymentType: json['PaymentType'] as String?,
      customerDob: json['CustomerDob'] as String?,
      idIssuePlace: json['IdIssuePlace'] as String?,
      idIssueDate: _fromJsonDateTime(json['IdIssueDate'] as String?),
      idType: json['IdType'] as String?,
      idDescription: json['IdDescription'] as String?,
      idExpiry: _fromJsonDateTime(json['IdExpiry'] as String?),
      phone: json['Phone'] as String?,
      address: json['Address'] as String?,
      companyName: json['CompanyName'] as String?,
      transactionService: json['TransactionService'] as String?,
      isIntegration: json['IsIntegration'] as String?,
    );

Map<String, dynamic> _$TransactionDetailsFzToJson(
        _TransactionDetailsFz instance) =>
    <String, dynamic>{
      'ReferenceNo': instance.transactionReference,
      'ChqNo': instance.chqNo,
      'TranDate': _toJsonDateTime(instance.transactionDate),
      'CustomerName': instance.customerName,
      'CustomerFirstName': instance.custFirstName,
      'CustomerMiddleName': instance.custMiddleName,
      'CustomerLastName': instance.custLastName,
      'BeneficiaryName': instance.beneficiaryName,
      'BenfName': instance.benfFirstName,
      'BenfName2': instance.benfMiddleName,
      'BenfName3': instance.benfLastName,
      'BenfCountry': instance.benfCountry,
      'BenfCurrencyCode': instance.toCurrencyCode,
      'CurrencyCode': instance.fromCurrencyCode,
      'AccountNo': instance.accountNumber,
      'BankName': instance.bankName,
      'FcyAmount': instance.paymentAmount,
      'LcyAmount': instance.receivedAmount,
      'Charges': instance.charge,
      'TaxAmount': instance.taxAmount,
      'NetAmount': instance.netAmount,
      'MultiplicationRate': instance.multiplicationRate,
      'BeneficiaryMobile': instance.beneficiaryMobile,
      'ServMode': instance.servMode,
      'PinNumber': instance.pinNumber,
      'PayMode': instance.payMode,
      'PayModeDesc': instance.payModeDesc,
      'PaymentStatus': instance.paymentStatus,
      'BneficiaryId': instance.bneficiaryId,
      'ServiceCode': instance.serviceCode,
      'ServiceType': instance.serviceType,
      'BenfActiveStatus': instance.benfActiveStatus,
      'ReadyForCancel': instance.readyForCancel,
      'TransactionStatus': instance.transactionStatus,
      'ServiceProvider': instance.serviceProvider,
      'PaymentRefNo': instance.paymentRefNo,
      'DivisionRate': instance.divisionRate,
      'Header': instance.header,
      'IsMobileTxn': instance.isMobileTxn,
      'IsCorrespondentActive': instance.isCorrespondentActive,
      'BranchName': instance.branchName,
      'Purpose': instance.purpose,
      'IfscCode': instance.ifscCode,
      'Rebate': instance.rebate,
      'BranchCode': instance.branchCode,
      'Customer': instance.customer,
      'Email': instance.email,
      'TaxCard': instance.taxCard,
      'CustomerVatin': instance.customerVatin,
      'ArieEmployeeFlag': instance.arieEmployeeFlag,
      'Relationship': instance.relationship,
      'DestinationCountryCode': instance.destinationCountryCode,
      'DestinationCountry': instance.destinationCountry,
      'CR': instance.cr,
      'CustomerNationality': instance.customerNationality,
      'CustomerNationalityCode': instance.customerNationalityCode,
      'Source': instance.source,
      'BeneficiaryNationality': instance.beneficiaryNationality,
      'BeneficiaryAddress': instance.beneficiaryAddress,
      'BeneficiaryCountryCode': instance.beneficiaryCountryCode,
      'Correspondent': instance.correspondent,
      'Profession': instance.profession,
      'BeneficiaryType': instance.beneficiaryType,
      'CustomerIdDescription': instance.customerIdDescription,
      'VisaType': instance.visaType,
      'CustomerType': instance.customerType,
      'BranchId': instance.branchId,
      'BirthCountryCode': instance.birthCountryCode,
      'BirthCountry': instance.birthCountry,
      'CustomerIdNo': instance.customerIdNo,
      'CustomerCode': instance.customerCode,
      'IsPep': instance.isPep,
      'IdCode': instance.idCode,
      'PaymentType': instance.paymentType,
      'CustomerDob': instance.customerDob,
      'IdIssuePlace': instance.idIssuePlace,
      'IdIssueDate': _toJsonDateTime(instance.idIssueDate),
      'IdType': instance.idType,
      'IdDescription': instance.idDescription,
      'IdExpiry': _toJsonDateTime(instance.idExpiry),
      'Phone': instance.phone,
      'Address': instance.address,
      'CompanyName': instance.companyName,
      'TransactionService': instance.transactionService,
      'IsIntegration': instance.isIntegration,
    };
