// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_kabayan_remit.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLk4Ps7qzi3Tc-YcR9LsuJd-d8U4Tnv1M',
    appId: '1:200925117312:web:e02c1f6b68e90d54995f65',
    messagingSenderId: '200925117312',
    projectId: 'city-exchange-b0ae0',
    authDomain: 'city-exchange-b0ae0.firebaseapp.com',
    storageBucket: 'city-exchange-b0ae0.firebasestorage.app',
    measurementId: 'G-DSW59ZRG0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpkCn7Scy1dqTISkj7L4AY3kaUb1OduxE',
    appId: '1:200925117312:android:b83282c10626a15a995f65',
    messagingSenderId: '200925117312',
    projectId: 'city-exchange-b0ae0',
    storageBucket: 'city-exchange-b0ae0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6Ohghuo0O0yIlfG8hepNSWXkZR79vEtU',
    appId: '1:200925117312:ios:2027f7073c8184a9995f65',
    messagingSenderId: '200925117312',
    projectId: 'city-exchange-b0ae0',
    storageBucket: 'city-exchange-b0ae0.firebasestorage.app',
    iosBundleId: 'com.dis.kabayanremit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6Ohghuo0O0yIlfG8hepNSWXkZR79vEtU',
    appId: '1:200925117312:ios:2027f7073c8184a9995f65',
    messagingSenderId: '200925117312',
    projectId: 'city-exchange-b0ae0',
    storageBucket: 'city-exchange-b0ae0.firebasestorage.app',
    iosBundleId: 'com.dis.kabayanremit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFViZB0r_zdsaMjiziWIPMiSpj8cx8Ahk',
    appId: '1:200925117312:web:d7207f0c23a11685995f65',
    messagingSenderId: '200925117312',
    projectId: 'city-exchange-b0ae0',
    authDomain: 'city-exchange-b0ae0.firebaseapp.com',
    storageBucket: 'city-exchange-b0ae0.firebasestorage.app',
    measurementId: 'G-9W2PG7V66T',
  );
}
