// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYjkROX5fSVY0CqNkDHStKBdykEg3homQ',
    appId: '1:19560521545:web:5c7371f266bd7058468498',
    messagingSenderId: '19560521545',
    projectId: 'casmex-53899',
    authDomain: 'casmex-53899.firebaseapp.com',
    storageBucket: 'casmex-53899.appspot.com',
    measurementId: 'G-XCHE879PD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyWoZEtt1A94xgwdx19wJQjzr4VKylyh4',
    appId: '1:19560521545:android:a211c7cc4f64621d468498',
    messagingSenderId: '19560521545',
    projectId: 'casmex-53899',
    storageBucket: 'casmex-53899.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6XaB2vzIbKmPqOCRm4q8QGB6bJx1r3Gg',
    appId: '1:19560521545:ios:b659b217c3bd4bab468498',
    messagingSenderId: '19560521545',
    projectId: 'casmex-53899',
    storageBucket: 'casmex-53899.appspot.com',
    iosBundleId: 'com.mobile.KabayanRemit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6XaB2vzIbKmPqOCRm4q8QGB6bJx1r3Gg',
    appId: '1:19560521545:ios:8cfa29555732a455468498',
    messagingSenderId: '19560521545',
    projectId: 'casmex-53899',
    storageBucket: 'casmex-53899.appspot.com',
    iosBundleId: 'com.dis.casmexMobile.RunnerTests',
  );
}
