// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_global_exchange_qatar.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoiis46CPrYPOCkyTjGK3owtKpfjW1UhM',
    appId: '1:416001812981:web:5eda63e40b7b9acc17d8bc',
    messagingSenderId: '416001812981',
    projectId: 'global-exchange-qatar',
    authDomain: 'global-exchange-qatar.firebaseapp.com',
    storageBucket: 'global-exchange-qatar.firebasestorage.app',
    measurementId: 'G-F4GBYNH5M9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVcbtXNte5biMOH1DjvwdAUPAw5aaCvrA',
    appId: '1:416001812981:android:788823a1feaecaa117d8bc',
    messagingSenderId: '416001812981',
    projectId: 'global-exchange-qatar',
    storageBucket: 'global-exchange-qatar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArPBeD-qayqPYhjOed8TvVq63fXc3uEBg',
    appId: '1:416001812981:ios:7bb8d59254920b5217d8bc',
    messagingSenderId: '416001812981',
    projectId: 'global-exchange-qatar',
    storageBucket: 'global-exchange-qatar.firebasestorage.app',
    iosBundleId: 'com.dis.globalexchange',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArPBeD-qayqPYhjOed8TvVq63fXc3uEBg',
    appId: '1:416001812981:ios:7bb8d59254920b5217d8bc',
    messagingSenderId: '416001812981',
    projectId: 'global-exchange-qatar',
    storageBucket: 'global-exchange-qatar.firebasestorage.app',
    iosBundleId: 'com.dis.globalexchange',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoiis46CPrYPOCkyTjGK3owtKpfjW1UhM',
    appId: '1:416001812981:web:dbf613a8be74c33f17d8bc',
    messagingSenderId: '416001812981',
    projectId: 'global-exchange-qatar',
    authDomain: 'global-exchange-qatar.firebaseapp.com',
    storageBucket: 'global-exchange-qatar.firebasestorage.app',
    measurementId: 'G-72H4LMDK1N',
  );
}
