// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_lmpay.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXtuLk83hIZAUhkvG_rVu_BMm9fMNOCK0',
    appId: '1:283893584957:web:4f701dacbffce6b8ac0654',
    messagingSenderId: '283893584957',
    projectId: 'lm-user-app',
    authDomain: 'lm-user-app.firebaseapp.com',
    databaseURL: 'https://lm-user-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lm-user-app.firebasestorage.app',
    measurementId: 'G-FNQV0BTRWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCegGjRgEHvMh9fZ7HSe2bl2ZN9zfwLAPg',
    appId: '1:283893584957:android:63f09d465eaf8489ac0654',
    messagingSenderId: '283893584957',
    projectId: 'lm-user-app',
    databaseURL: 'https://lm-user-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lm-user-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB9H-uuWbglPaECwkR0j_OojonM6Z5e1c',
    appId: '1:283893584957:ios:5b41ef474f6de0b9ac0654',
    messagingSenderId: '283893584957',
    projectId: 'lm-user-app',
    databaseURL: 'https://lm-user-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lm-user-app.firebasestorage.app',
    iosBundleId: 'com.user.lmpay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB9H-uuWbglPaECwkR0j_OojonM6Z5e1c',
    appId: '1:283893584957:ios:5b41ef474f6de0b9ac0654',
    messagingSenderId: '283893584957',
    projectId: 'lm-user-app',
    databaseURL: 'https://lm-user-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lm-user-app.firebasestorage.app',
    iosBundleId: 'com.user.lmpay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiL4iLWGl7POVW8FIW0MhllUb3OCaqLhA',
    appId: '1:283893584957:web:a2032f9f5464341fac0654',
    messagingSenderId: '283893584957',
    projectId: 'lm-user-app',
    authDomain: 'lm-user-app.firebaseapp.com',
    databaseURL: 'https://lm-user-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lm-user-app.firebasestorage.app',
    measurementId: 'G-EQZCVRDFPS',
  );
}
