import '../core/exports/ui_two_pages.dart';

dynamic uiTwoRoutes = {
  AppRoutes.splashScreen: const SplashScreen(),
  AppRoutes.selectLanguage: const SelectLanguage(
    firstLaunch: true,
  ),
  AppRoutes.intro: IntroPage(),
  AppRoutes.preLogin: const PreLogin(),
  AppRoutes.nid: const NIDFormRulesPage(),
  AppRoutes.uploadDocuments: const UploadDocumentPage(),
  AppRoutes.selfie: const UploadSelfiePage(),
  AppRoutes.videoKyc: const UploadVideoKYCPage(),
  AppRoutes.login: LoginPage(),
  AppRoutes.loginMPIN: LoginMPIN(),
  AppRoutes.accountType: AccountTypePage(),
  AppRoutes.dashboard: DashBoardPageTheme1(),
  AppRoutes.eSignature: ESignaturePage(),
  AppRoutes.faceRecognition: FaceRecognitionPage(),
  AppRoutes.forgotMPIN: ForgotMpinFormRule(),
  AppRoutes.changeMPIN: ChangeMpinFormRule(),
  AppRoutes.changePassword: ChangePasswordFormRule(),
  AppRoutes.forgotUsername: ForgotUsernameFormRule(),
  AppRoutes.resetCredentials: ResetCredentials(),
  AppRoutes.main: MainPage(),
  AppRoutes.resetMpin: ResetMpinPage(),
  AppRoutes.securitySettings: SecuritySettingsPage(),
  AppRoutes.signUp: SignUpFormRulesPage(),
  AppRoutes.setCredentials: SetCredentialsFormRulesPage(),
  AppRoutes.identityVerification: IdentityVerificationFormRulesPage(),
  AppRoutes.settings: SettingsPage(),
  AppRoutes.loadingRoutes: LoadingPage(),
  AppRoutes.docShareRetryRoutes: DocShareRetry(),
  AppRoutes.visualizationRetryRoutes: RetryVisualization(),
  AppRoutes.notificationNotExpiredRetryRoutes: NotificationNotExpiredRetry(),
  AppRoutes.visualizationRetryRoutesUAEPASS:
      DocShareRetryVisualizationUaepass(),
  AppRoutes.notificationNotExpiredRetryRoutesUAEPASS:
      NotificationNotExpiredRetryUaepass(),
  AppRoutes.myBeneficiary: MyBeneficiaryPage(),
  AppRoutes.archivedBeneficiary: ArchivedBeneficiariespage(),
  AppRoutes.myTransaction: MyTransactionsPageUiTwo(),
  AppRoutes.sendMoney: SendMoneyPage1(),
  AppRoutes.confirmPaymentDetails: ConfirmDetailsPage(),
  AppRoutes.forexRates: ForexRatesPage(),
  //Account Pages
  AppRoutes.myProfile: MyProfilePage(),
  AppRoutes.contactUs: ContactUsPage(),
  AppRoutes.aboutUs: AboutUsPage(),
  AppRoutes.termConditions: TermsAndConditionsPage(),
  AppRoutes.privacyPolicy: PrivacyPolicyPage(),
  AppRoutes.resetPassword: ResetCredentials(),
  AppRoutes.createAlert: CreateAlertPage(),
  AppRoutes.currencyRates: CurrencyRatesPage(),
};
