import java.util.Properties
import java.io.FileInputStream

plugins {
    id("com.android.application")
    id("kotlin-android")
    id("dev.flutter.flutter-gradle-plugin")
    id("com.google.gms.google-services")
    id("com.google.firebase.crashlytics")
}

// ---- Read local.properties for Flutter versioning ----
val localProperties = Properties().apply {
    val f = rootProject.file("local.properties")
    if (f.exists()) {
        f.inputStream().use { load(it) }
    }
}

val flutterVersionCode: Int = localProperties.getProperty("flutter.versionCode")?.toInt() ?: 1
val flutterVersionName: String = localProperties.getProperty("flutter.versionName") ?: "1.0"


val jazeeraProperties = Properties().apply {
    val f = rootProject.file("jazeera_key.properties")
    if (f.exists()) FileInputStream(f).use { load(it) }
}

val hamdanProperties = Properties().apply {
    val f = rootProject.file("hamdan_hexpay.properties")
    if (f.exists()) FileInputStream(f).use { load(it) }
}

android {
    namespace = "com.dis.casmex"
    compileSdk = 36
    ndkVersion = "29.0.14206865"

    configurations.all {
        resolutionStrategy {
            force(
                "com.google.firebase:firebase-iid:21.1.0",
                "com.google.firebase:firebase-messaging:23.0.0"
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        isCoreLibraryDesugaringEnabled = true
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }

    sourceSets {
        getByName("main") {
            java.srcDirs("src/main/kotlin")
        }
    }

    defaultConfig {
        minSdk = 29
        targetSdk = 36
        versionCode = flutterVersionCode
        versionName = flutterVersionName
        multiDexEnabled = true
         ndk {
             abiFilters += listOf("armeabi-v7a", "arm64-v8a")
         }
    }

    signingConfigs {
        create("release") {
            keyAlias = hamdanProperties["keyAlias"]?.toString()
            keyPassword = hamdanProperties["keyPassword"]?.toString()
            storeFile = hamdanProperties["storeFile"]?.toString()?.let { file(it) }
            storePassword = hamdanProperties["storePassword"]?.toString()
        }
//        create("debug") {
//            keyAlias = hamdanProperties["keyAlias"]?.toString()
//            keyPassword = hamdanProperties["keyPassword"]?.toString()
//            storeFile = hamdanProperties["storeFile"]?.toString()?.let { file(it) }
//            storePassword = hamdanProperties["storePassword"]?.toString()
//        }
    }

    buildTypes {
        getByName("release") {
            signingConfig = signingConfigs.getByName("release")
            isMinifyEnabled = false
            isShrinkResources = false
        }
        getByName("debug") {
            signingConfig = signingConfigs.getByName("debug")
        }
    }
}

flutter {
    source = "../.."
}

dependencies {
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.5")
    implementation("androidx.activity:activity-ktx:1.8.2")
    implementation("androidx.core:core-ktx:1.12.0")
    implementation("androidx.multidex:multidex:2.0.1")
}

// ----- BEGIN flavorDimensions (autogenerated by flutter_flavorizr) -----
apply { from("flavorizr.gradle.kts") }
// ----- END flavorDimensions (autogenerated by flutter_flavorizr) -----